services:
  - type: web
    name: meditation-room-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true